fix: prevent repo from stop being handled
Attempted fix of errors like:
Error creating agent for PushEvent.: failed to create agent: failed to calculate in repo config: failed to load trigger config for repository jenkins-x/jx3-versions for ref : failed to switch to ref : failed to merge repository jenkins-x/jx3-versions: failed to run command in dir /var/tmp/gitrepo2428068395: git, [merge FETCH_HEAD]: Updating 3e21ade2..3bebed28
error: Your local changes to the following files would be overwritten by merge:
	src/get-selectors-and-clean.sh
Please commit your changes or stash them before you merge.
Aborting: exit status 1

Explanation:
--no-checkout stages the deletion of all files which causes problem when merging upstreams changes to working directory. This is fixed by bypassing working directory when fetching upstreams changes to local branch no conflict occurs. Conflicts are then ignored during checking out with --force.

also stop using deprecated diff.ObjectReflectDiff